Check early if the CoreOS image even exists.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,6 +5,7 @@ set -e -o pipefail
 # Ensure that required executables exist before proceeding
 which tar >/dev/null || fatal "tar not found"
 which xz >/dev/null || fatal "xz not found"
+which egrep >/dev/null || fatal "egrep not found"
 
 PACKER_VERSION="0.7.5"
 
@@ -17,6 +18,15 @@ if echo "${PLATFORMS[@]}" | egrep -q "\bamazon.*" || [ -z "${PLATFORMS[@]}" ]; t
 	test -n "$AWS_X509_KEY" || AWS_X509_KEY="$BASE/aws_key.pem"
 	test -f "$AWS_X509_CERT" || fatal "AWS X509 certificate not found at '$AWS_X509_CERT'."
 	test -f "$AWS_X509_KEY" || fatal "AWS X509 key not found at '$AWS_X509_KEY'."
+
+	# Does the expected image even exist?
+	local channel=$(echo $USERDATA | egrep -o 'channel=[a-z]+' | cut -d '=' -f 2)
+	channel=${channel:-${CHANNEL}}
+	local version=$(echo $USERDATA | egrep -o 'version=[0-9.]+' | cut -d '=' -f 2)
+	version=${version:-${VERSION}}
+	local coreos_source_image_url="http://${channel}.release.core-os.net/amd64-usr/${version}/coreos_production_ami_image.bin.bz2"
+	curl --fail -sI ${coreos_source_image_url} >/dev/null \
+	|| fatal "Image URL unavailable: ${coreos_source_image_url}"
 
 	local tools_tarball="files/tools.tar.xz"
 	tar --exclude '.*' -cJf ${tools_tarball} tools
